name: Setup docker

runs:
  using: composite
  steps:
    - name: Setup cosign environment
      uses: sigstore/cosign-installer@7e0881f8fe90b25e305bbf0309761e9314607e25

    - name: Setup QEMU environment
      uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8

    - name: Setup buildx environment
      uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6
