name: nodejs publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: init nodejs
        uses: ./.github/actions/init
        with:
          nodejs-version: ${{ matrix.node-version }}
      - name: test
        shell: bash
        run: npm test

  # don't use registry.npmjs.org
  # publish-npm:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: init nodejs
        uses: ./.github/actions/init
        with:
          nodejs-version: ${{ matrix.node-version }}
      - name: publish
        shell: bash
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
