name: Nodejs CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 15 * * 0"

permissions: read-all

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0

      - name: Setup nodejs environment
        uses: ./.github/actions/init
        with:
          nodejs-version: ${{ matrix.node-version }}

      - name: Build
        shell: bash
        run: npm run build --if-present

      - name: Test
        shell: bash
        run: npm test
